#!/bin/sh

### BEGIN INIT INFO
# Provides:          httpd
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the apache web server
# Description:       starts apache web server using start-stop-daemon
### END INIT INFO

. /usr/local/apache2/bin/apachectl
