#!/bin/bash

[[ -d /usr/local/var/lib/logrotate ]] || mkdir -p /usr/local/var/lib/logrotate
[[ -d /usr/local/etc/logrotate.d ]] || mkdir -p /usr/local/etc/logrotate.d

# Clean non existent log file entries from status file
cd /usr/local/var/lib/logrotate
test -e status || touch status
head -1 status > status.clean
sed 's/"//g' status | while read logfile date
do
    [ -e "$logfile" ] && echo "\"$logfile\" $date"
done >> status.clean
mv status.clean status

test -x /usr/sbin/logrotate || exit 0
/usr/sbin/logrotate /usr/local/etc/logrotate.d/
