---

- name: Apply common configuration to all nodes
  hosts: all
  vars:
      user:    '{{ ansible_ssh_user }}'
      www_user: www-data
      app_env: 'prod'
  roles:
    - common

- name: Configure application support
  hosts: app
  vars:
      user:    '{{ ansible_ssh_user }}'
      www_user: www-data
  roles:
    - app
