---

- name:       'Crossbar : Install dependency packages'
  sudo:       yes
  apt:        pkg={{ item }} state=installed
  with_items:
    - libffi-dev

- name:       Install crossbar.io
  pip:        name=crossbar
  sudo:       yes
