---

- name:       Create user bin directory
  file:       path=/home/{{ user }}/bin state=directory

- name:       Clone KNP Labs symfony2-autocomplete
  git:        repo=https://github.com/KnpLabs/symfony2-autocomplete dest=/home/{{ user }}/bin/symfony2-autocomplete

- name:       Add to .bashrc
  lineinfile: dest=/home/{{ user }}/.bashrc line='source ~/bin/symfony2-autocomplete/symfony2-autocomplete.bash'
